name: Run Selenium Scripts Daily
on:
  schedule:
    - cron: '0/5 * * * *' # Runs daily at midnight
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install pandas
          pip install pytest
          pip install pytest-html
          pip install pytest-xdist
          pip install pyyaml
          pip install softest
          pip install logging
          pip install openpyxl
      - name: Run Selenium script
        run: pytest testcases/test_bht.py
      - run: |
          git config user.name "aravind.raja"
          git config user.email "aravinda.ec@gmail.com"
          git add logs/test_log.log
          git add screenshots
          git add reports
          git commit -m "Update logs and screenshots"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/aravindarajum/dailybht_V2.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
